#!/bin/sh

#### Constants
MACHINE_NAME=private-cloud
REGISTRY=redis
VERSION=3.0.7-alpine
DB_HOME=/usr/local

MACHINE_ON=$(docker-machine ls | grep $MACHINE_NAME)
if [[ "$MACHINE_ON" == *"Running"* ]]
then
	eval "$(docker-machine env $MACHINE_NAME)"
fi

#### Main
until docker run \
        --rm \
        --net bridge \
        --entrypoint $DB_HOME/bin/redis-cli \
        -it ${REGISTRY}:${VERSION} \
        -h $1
do
        echo "*** waiting another 10s for db to start,..."
        sleep 10
done